name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run distcheck
      run: sudo apt-get -y install gcc make gettext zlib1g-dev libncurses5-dev bison flex bc texinfo tree cmake flex

    - name: Make
      run: source ./env.sh && make hiboot && make build
